services:
  - type: web
    name: fastapi-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: TURSO_DATABASE_URL
        value: libsql://sample-siranjeevan.aws-ap-south-1.turso.io
      - key: TURSO_AUTH_TOKEN
        value: eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJhIjoicnciLCJpYXQiOjE3NjM1NjQ3MzQsImlkIjoiODE1YTI4MTktOTkyMS00NDU0LWIwODYtZmI4NDNhODA2OGZmIiwicmlkIjoiZTZlZmNmMmEtOTVlNC00ZmRlLTlkNjQtZTRkNjg1MDc2Mzc2In0.WWBDM9Y7DkaKUBmDhnFrNiO-sEJT-vAwm4SPF2MNZ_dkWvEz98w90rZm30P0XC6KU-Lh-O54nKff42GyyBLNAg